service: gcs-watcher     # see https://cloud.google.com/appengine/docs/go/
runtime: go              # see https://cloud.google.com/appengine/docs/go/
api_version: go1         # used when appengine supports different go versions

# default_expiration: "1d"        # for CDN serving of static files (use url versioning if long!)

handlers:
- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

nobuild_files:
- vendor/

skip_files:
- vendor/
